"""Exact square-class filters for the Bremner--Silverman--Tzanakis route.

The target for a magic square is stronger than an arithmetic progression of
points: each point Q=(x,y) must lie in 2E(K).  For

    E_n: y^2 = x(x^2-n^2)

the full-2-descent/Kummer criterion tests x-n, x, and x+n.  This module keeps
the rational square-class computations used in BST_NUMBER_FIELD_ANALYSIS.md
small, exact, and reproducible.
"""

from __future__ import annotations

import math
from collections.abc import Iterable

from sympy import factorint

from spearman_kummer import squarefree_part


def kummer_squareclasses(x: int, n: int) -> tuple[int, int, int]:
    """Return squarefree representatives of x-n, x, x+n over Q.

    Zero is retained as zero; it occurs at a rational 2-torsion point and has
    to be interpreted with the usual special Kummer convention.
    """

    return tuple(0 if value == 0 else squarefree_part(value) for value in (x - n, x, x + n))


def _class_support(squarefree: int) -> frozenset[int]:
    """Encode a rational square class as a set of F_2 basis labels."""

    if squarefree == 0:
        return frozenset()
    labels: set[int] = set()
    if squarefree < 0:
        labels.add(-1)
    labels.update(int(prime) for prime in factorint(abs(squarefree)))
    return frozenset(labels)


def squareclass_rank(classes: Iterable[int]) -> int:
    """Dimension of the subgroup of Q*/Q*2 generated by nonzero classes."""

    supports = [_class_support(value) for value in classes if value not in (0, 1)]
    labels = sorted(set().union(*supports)) if supports else []
    pivots: dict[int, int] = {}
    rank = 0
    for support in supports:
        vector = sum(1 << index for index, label in enumerate(labels) if label in support)
        while vector:
            pivot = vector.bit_length() - 1
            if pivot not in pivots:
                pivots[pivot] = vector
                rank += 1
                break
            vector ^= pivots[pivot]
    return rank


def bst_torsion_family_parameter(r: int, s: int) -> int:
    """The signed n/t^2 in BST Theorem 1.3."""

    if r == 0 or s == 0 or math.gcd(r, s) != 1:
        raise ValueError("r and s must be nonzero and coprime")
    return 3 * (r * r + s * s) * (r * r - 2 * s * s) * (2 * r * r - s * s)


def valuation(value: int, prime: int) -> int:
    """Return v_prime(value) for a nonzero integer."""

    if value == 0 or prime < 2:
        raise ValueError("require a nonzero value and a prime >= 2")
    exponent = 0
    value = abs(value)
    while value % prime == 0:
        value //= prime
        exponent += 1
    return exponent


def bst_parameter_has_odd_three_valuation(r: int, s: int) -> bool:
    """Verify the 3-adic obstruction for coprime BST parameters.

    For coprime r,s, none of r^2+s^2, r^2-2s^2, 2r^2-s^2 is divisible by
    3.  Hence the displayed factor 3 is the complete 3-part modulo squares;
    multiplying by BST's rational t^2 cannot change this parity.
    """

    return valuation(bst_torsion_family_parameter(r, s), 3) % 2 == 1


def known_1254_squareclass_data() -> tuple[tuple[int, tuple[int, int, int]], ...]:
    """Kummer data for BST's non-torsion integral AP on E_1254."""

    return tuple((x, kummer_squareclasses(x, 1254)) for x in (-528, -363, -198))


def known_1254_common_halving_degree() -> int:
    """Degree of the multiquadratic field generated by all required roots."""

    classes = (value for _, triple in known_1254_squareclass_data() for value in triple)
    return 2 ** squareclass_rank(classes)

